# Preprocessing functions
## In this notebook there are somo useful funcions to work with datasets with pandas making transformation over the dataset and preprocessing some columns or rows to work with.

In [1]:
import pandas as pd
import numpy as np

Loading example data sets

In [9]:
df_cities = pd.read_csv('../../datasets/Uk_cities.csv')

### Apply funcions

In [ ]:
df_name.apply(np.sqrt)
df_name.apply(np.sum, axis=0)
df_name.apply(lambda x: [1, 2], axis=1)
df_name.apply(lambda x: pd.Series([1, 2], index=['column1', 'column2']), axis=1)
df_name.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
df_name.apply(name_fun, argument1= 0, argument2=5)
#arguments could be by position or specific
df.applymap(lambda x: len(str(x)))
#Apply a function to a Dataframe elementwise

In [ ]:
df = df.apply(lambda x: funcion(x) if(np.all(pd.notnull(x[0]))) else x, axis = 1)
#apply a funcion over a dataframe if the values is not null

### Apply functions over text type columns

In [ ]:
df_name['column1'].str.lower()
# conevert all strings in column1 to lower case 
df_name['column1'].str.upper()
#conevert all strings in column1 to upper case 
df_name['column1'].str.capitalize()
#conevert all strings in column1 to capitalize
df_name['column1'].str.len()
#diplays len of all string in column1
df_name['column1'].str.split(' ')
# divide all strings with a caracter, in this case with a empty space 
df_name['column1'].str[:5]
# select the first 5 caracters of a string
df_name['column1'].str[-5:]
# select the last 5 caracters of a string
df_name['column1'].str.replace('strng1','new_string1')
#remplace strings
df_name['column1'].str.findall('ara')
#find  in all string the secuence of ccaracter 'ara'
df_name['column1']str.startswith('b')
df_name['column1']str.endswith('a')
df_name['column1'].str.contains('or')
#displays true in all strings that contain 'or'
df_name['column1'].str.count('a')
#count all elements a in all strings
df_name['column1'].str.extract('([0-9]+)', expand=False)
df_name['column1'].str.extractall(r"[ab](\d)")
# extract all alfanumeric alements 
df_name['column1'].str.replace('@[^\s]+','')
df_name['column1'].str.zfill(3)
# add 0 equal to 3 in all strings
df_name['column1'].str.wrap(12)
#Wrap long strings to be formatted in paragraphs, max lenth 12
df_name['column1'].str.title
#convert a string to title
df_name['column1'].str.swapcase
#convert a string to swapcase
df_name['column1'].str.strip()
#delete empty spaces
df_name['column1'].str.strip('\n\f.!?')
#delete empty spaces and salected caracters
df_name['column1'].str.split()
#transform a string to list 
df_name['column1'].str.split(pat = "/")
#transform a string to list where /
df_name['column1'].str.repeat(repeats=2)
df_name['column1'].str.isupper()
df_name['column1'].str.istitle()
df_name['column1'].str.isspace()
df_name['column1'].str.isnumeric()
df_name['column1'].str.islower()
df_name['column1'].str.isdigit()
df_name['column1'].str.isdecimal()
df_name['column1'].str.isalpha()
df_name['column1'].str.isnum()
df_name['column1'].str.index()
#Return lowest indexes in each strings
df_name['column1'].str.get(1)
#get first elemnt to a string
#more information in
r'https://pandas.pydata.org/docs/search.html?q=str'

example: when you have a column with string values like cities but there are a specific city wrote it in diferents ways like: 'city London', 'City London', 'London', 'City Of London' etc.

In [13]:
df_cities.sample(5)

city  \
724           City Of London   
656                 Bradford   
569                Edinburgh   
978                   London   
266  London Heathrow Airport   

                                        salary_offered  
724                       £38,000 - £42,000 per annum   
656                   £18,000 per annum, inc benefits   
569   £32,000 - £42,000 per annum, negotiable, inc ...  
978                                Competitive salary   
266                           £9.00 - £10.00 per hour

In [14]:
df_cities['city'] = df_cities['city'].replace(to_replace=r'([a-zA-Z]*\s)*London', value='London', regex=True)

In [20]:
df_cities.sample(5)

city                 salary_offered
234     London   £35,000 - £40,000 per annum 
939  Harrogate             Salary negotiable 
785      Leeds             Salary negotiable 
466     London            Competitive salary 
631    Evesham   £30,000 - £31,500 per annum

example: when you have a column with numerical values like salaries but wrote it in diferents ways like: '£35,000 - £40,000 per annum', '£9.00 - £10.00 per hour', '£18,000 per annum, inc benefits', '£7.50 per hour'.

In [21]:
s = df_cities['salary_offered']
list_with_range_sannum = s.str.extract(r'£([0-9]+,[0-9]+)\s-\s£([0-9]+,[0-9]+)\s\w+\sannum')
list_with_range_sannum[0] = list_with_range_sannum[0].str.replace(',', '')
list_with_range_sannum[1] = list_with_range_sannum[1].str.replace(',', '')
def mean(row):
    """"this funcion resive a df and return the mean over the values in the column 1 and column 2 by each row"""
    return (int(row[0]) + int(row[1]))//2
list_with_range_sannum = list_with_range_sannum.apply(lambda x: mean(x) if(np.all(pd.notnull(x[1]))) else x, axis = 1)
list_with_range_sannum.head()
#  Salaries with range and per annum

0        1
0      NaN      NaN
1  20000.0  20000.0
2      NaN      NaN
3  16000.0  16000.0
4  41000.0  41000.0

In [22]:
list_with_sannum = s.str.extract(r'£([0-9]+,[0-9]+)\s\w+\sannum')
list_with_sannum[0] = list_with_sannum[0].str.replace(',', '')
list_with_sannum.head()
# Salaries per annum

0
0  18323
1  22000
2    NaN
3  17000
4  45000

In [37]:
list_with_hour = s.str.extract(r'£([0-9]+\.[0-9]+)\s-\s£([0-9]+\.[0-9]+)\s\w+\shour')
def mean2(row):
    aux = (float(row[0]) + float(row[1]))/2
    aux2 = aux*2080
    return aux2
list_with_range_hour = list_with_hour.apply(lambda x: mean2(x) if(np.all(pd.notnull(x[1]))) else x, axis = 1)
list_with_range_hour.sample(5)
# Salaries with range per hour

0        1
575  15943.2  15943.2
401  19760.0  19760.0
944      NaN      NaN
862      NaN      NaN
925      NaN      NaN

In [40]:
list_with_hour_2 = s.str.extract(r'£([0-9]+\.[0-9]+)\s\w+\shour')
def to_sannum(row):
    aux = float(row[0])*2080
    return aux
list_with_hour_2 = list_with_hour_2.apply(lambda x: to_sannum(x) if(np.all(pd.notnull(x[0]))) else x, axis = 1)
list_with_hour_2.sample(5)

0
175  15600.0
419      NaN
72       NaN
958  47881.6
667      NaN

mix all 

In [41]:
salary = list_with_range_sannum[0]
salary = pd.DataFrame(data=salary)
salary[1]= list_with_sannum[0]
salary2 = salary.apply(lambda x: x[1] if(np.all(pd.isnull(x[0]))) else x[0], axis = 1)
salary2 = pd.DataFrame(data=salary2)
salary2[1]= list_with_range_hour[0]
salary3 = salary2.apply(lambda x: x[1] if(np.all(pd.isnull(x[0]))) else x[0], axis = 1)
salary3 = pd.DataFrame(data=salary3)
salary3[1]= list_with_hour_2[0]
salary4 = salary3.apply(lambda x: x[1] if(np.all(pd.isnull(x[0]))) else x[0], axis = 1)
salary4 = pd.DataFrame(data=salary4)
salary4.head

<bound method NDFrame.head of           0
0     18323
1     20000
2       NaN
3     16000
4     41000
...     ...
996   47500
997   34000
998   19500
999   75000
1000  30000

[1001 rows x 1 columns]>

### Group by

In [ ]:
df_name.groupby('column1')
#displays a table where column 1 is a column of index and its values ​​change to indexes
df_name.groupby('column1').media()
df_name.groupby('column1').mean()
df_name = df_name.groupby(['city']).median(numeric_only=True)

In [ ]:
# group by multiple elements
df_name.groupby('column1')['column2']
df_name.groupby('column1')['column2'].count()
df_name.groupby('column1')['column2'].max()
df_name.groupby('column1')['column2'].min()
df_name.groupby(['column1','column2'])
df_name.groupby(['column1','column2'])['column3'].mean()

In [ ]:
df_name.groupby(['column1','column2'])['column3'].mean().to_frame()
# conver a grupby to a data frame
df_name.groupby(['column1','column2'])['column3'].aggregate(['min',np.mean,max])
dict_agg={'column3':[min,max]}, 'column4':[np.mean, my_fun]
df_name.groupby(['column1','column2']).aggregate(dict_agg)
df_name-groupby('column1')[['column2']].describe()
df_name-groupby('column1')[['column2']].apply(my_fun)
# . apply only one funcion and aggregate for many funcions
# apply funcions 
# more information in:
r'https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html?highlight=groupby#pandas.DataFrame.groupby'
r'https://platzi.com/clases/1794-pandas/27898-aggregation-y-groupby/'

In [ ]:
# apply filter
def f_filter(x):
 return np.mean(x[column2])>4
df_name.groupby('column1').filter(f_filter)
#more information in:
r'https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.filter.html?highlight=filter#pandas.core.groupby.DataFrameGroupBy.filter'
r'https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.filter.html?highlight=filter#pandas.DataFrame.filter'

### sort

In [ ]:
df_name = df_name.groupby(['column']).count()
df_name = df_name.sort_values(by=['column'], ascending=False)
df_name.sort_idex()
df_name.sort_values(ascending=False)

### Apply functions over Time series type columns

In [ ]:
df1-df2
# display the diferneces betwent values of df1 and df2 dipendiong of the index 
# if no not have the same index displays null
df_name.diff()
#displays the diverences betwen index=time
df_name.diff().mean()
#by default the first element is null because do not have other element to compare
df_name.fillna({'column1':23,'column2':23})
# for that reason we should introduce its values with funcion fillna
df_name.cumsum()
#return cumulative sum over a DataFrame
#more information in:
r'https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cumsum.html?highlight=cumsum#pandas.DataFrame.cumsum'

In [ ]:
df_name.resample('7D').mean
df_name.resample('W-sun').sum(min_count=1)
df_name.resample('W-sun').sum()
df_name.resample('M').count()
# displays information in timeslots
#more information in:
r'https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html?highlight=resample#pandas.DataFrame.resample'

In [ ]:
df_name.groupby(pd.Grouper(key='timecolumn', freq='M'))[['column1']].mean()
# Grouper is a very usefull funcion that work it a column wuere values are type time
df_name.groupby(pd.Grouper(key='timecolumn', freq='1D'))[['column1']].mean()
#more information in:
r'https://pandas.pydata.org/docs/reference/api/pandas.Grouper.html?highlight=grouper#pandas.Grouper'

In [ ]:
df_name['timecolumn'].rolling('2s')
# rolling create a windows in columns with values type time 
# space betwen windows are two seconds in this case
# rolling is veri usefull to apply funcions and plot
df_name['timecolumn'].rolling(window=14).apply(lambda x: np.std(x)).plot()
#more information in:
r'https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html?highlight=rolling#pandas.DataFrame.rolling'
r'https://platzi.com/clases/1794-pandas/27894-series-de-tiempo-variables-nulas/'

### Work with duplicate data

In [ ]:
df.duplicated()
#displays all duplicate values
df.duplicated(keep='first')
# displays as a true only first councidence
df.duplicated(keep='last')
# displays as a true only last councidence
df[~ df.duplicated()]
# filter and displays all elementes that not are duplicates
df.duplicated(keep=False)
df[df.duplicated(keep=False)]
#displays duplicate elements
df.drop_duplicates()
df.drop_duplicates(['column1'],keep='last')
#more information in:
r'https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html?highlight=duplicate'

### Work with null data

In [ ]:
df_name.isnull()
df_name.isna()
df_name.isnull().sum()
# displays all elemnents null by column
df_name.notnull().sum(axis=1)
# displays all elemnents null by idex
df_name.size-df.isnull().sum().sum()
#all elemnts null in the data frame
df_name[df_name['a'].notnull()]
#filter by null elemnts

In [ ]:
df.dropna()
df[['a']].dropna()
df.fillna(0)
# replace all null elements with 0
df_name.fillna(method="ffill")
#replace all null elements with following value
df_name.fillna(method="bfill")
#replace all null elements with previus value
fill = pd.Series([100, 101, 102])
df_name['column1'] = df_name['column1'].fillna(fill)
#replace all null elements with serie(fill)
df_name.fillna(df.median())
#replace all null elements with media
df_New_name = pd.concat([df_name[['column1']], df_name[['column1']].interpolate()],axis=1)
df_New_name.columns = ['d_antes','d_interpolado']
#replace all null elements with a interpolation
#more infroamtion 
r'https://pandas.pydata.org/docs/search.html?q=null'

In [ ]:
df_name.notnull().apply(pd.Series.value_counts)
(df_name !=0).apply(pd.Series.value_counts)
filtro = ((df_name !=0) & (df_name.notnull()))
filtro.all(axis=1).values_counts()
mask = filtro['column1']
df_name = df_name[mask]

Function to split a dataset in three datasets
1. dataset columns with null data
2. dataset with with columns with not null data
3. dataset with columns with null and not null data

In [43]:
def split_dataset(df):
    rows_df = df.shape[0]
    columns_with_null_data = []
    columns_with_not_nul_data = []
    other_columns = []
    for column in df.columns:
        if df[column].isnull().sum() == rows_df:
            columns_with_null_data.append(column)
        elif df[column].isnull().sum() == 0:
            columns_with_not_null_data.append(column)
        else:
            other_columns.append(column)
    return columns_with_null_data, columns_with_not_null_data, other_columns

In [44]:
def diplay_groups(columns_with_null_data, columns_with_not_null_data, other_columns):
    print(f'The number of columns with null data in all its rows is: {len(columns_with_null_data)}')
    print(f'The number of columns with not null data in all its rows is: {len(columns_with_not_null_data)}')
    print(f'The number of columns with null data and with not null data is: {len(other_columns)}')

In [ ]:
columns_with_null_data, columns_with_not_null_data, other_columns = split_dataset(df_name)
diplay_groups(columns_with_null_data, columns_with_not_null_data, other_columns)

Funcion to check if two lists have the same elements (columns)

In [46]:
def same_columns(list_columns1, list_columns2):
    same_list = []
    for element1 in list_columns1:
        for element2 in list_columns2:
            if element1 == element2:
                same_list.append(element2)
    return same_list

In [ ]:
same_list = same_columns(list_columns1, list_columns2)

Funcion to double check if all columns in a diferents diferents columns list are the same

In [ ]:
def double_check(same_list, columns_with_null_data1, columns_with_null_data2,columns_with_nulldata3):
    A = same_columns(same_list, columns_with_null_data1)
    B = same_columns(same_list, columns_with_null_data2)
    C = same_columns(same_list, columns_with_null_data3)
    if len(A)==len(B) and len(B)==len(C):
        print('This have null data in all its rows. You could drop it.')